name: r_sears_mobile

description: Rwanda Smart Emergency Accident Response System mobile app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  geolocator: ^12.0.0
  permission_handler: ^11.0.0
  google_maps_flutter: ^2.7.0

flutter:
  uses-material-design: true
